FlightMVC/Controllers/FlightTravelClassesController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using OnilneFlightBooking.Entity;
using OnlineFlightBooking.BL;
using OnlineFlightBooking.Models;

namespace OnlineFlightBooking.Controllers
{
    public class FlightTravelClassesController : Controller
    {
        IFlightBL flightBL;
        public FlightTravelClassesController()
        {
            flightBL = new FlightBL(); 
        }
        // GET: FlightTravelClasses
        public ActionResult DisplayClass()
        {
            int flightId = Convert.ToInt32(TempData["FlightId"]);
            IEnumerable<FlightTravelClass> TravelClass = flightBL.DisplayClass(flightId);
            return View(TravelClass);       
        }
        // GET: FlightTravelClasses/GetTravelClass
        [HttpGet]
        public ActionResult CreateClass()
        {
            FlightTravelClass flightTravelClass = new FlightTravelClass();
            flightTravelClass.FlightId = Convert.ToInt32(TempData["FlightId"]);
            ViewBag.ClassId = new SelectList(flightBL.GetTravelClass(),"ClassId", "ClassName");
            FlightTravelClassModel flightTravelClassModel= AutoMapper.Mapper.Map<FlightTravelClass, FlightTravelClassModel>(flightTravelClass);     //Auto Mapper entity to model
            return View(flightTravelClassModel);
        }
        // POST: FlightTravelClasses/GetTravelClass
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateClass( FlightTravelClassModel flightTravelClassModel)
        {
            if (ModelState.IsValid)     //condition pass when all the model state validation is true
            {
                FlightTravelClass create = AutoMapper.Mapper.Map<FlightTravelClassModel,FlightTravelClass>(flightTravelClassModel);     //Auto Mapper model to entity
                
                flightBL.CreateClass(create);
                TempData["FlightId"] = create.FlightId;
                return RedirectToAction("DisplayFlight","Flight");
            }
            ViewBag.Class_Id = new SelectList(flightBL.GetTravelClass(), "ClassId", "ClassName", flightTravelClassModel.ClassId);
            return View(flightTravelClassModel);            //Calling View for the Create Class(when the ModelState is in valid)
        }
        [HttpGet]
        // GET: FlightTravelClasses/Edit/5
        public ActionResult EditClass(int id)
        {
            FlightTravelClass flightTravelClass =flightBL.GetDetailsClass(id);
            IEnumerable<TravelClass> travelClass=flightBL.GetTravelClass();
            ViewBag.ClassId = new SelectList(travelClass, "ClassId", "ClassName");
            FlightTravelClassModel flightTravelClassModel = AutoMapper.Mapper.Map<FlightTravelClass, FlightTravelClassModel>(flightTravelClass);       //Auto Mapper entity to model
            return View(flightTravelClassModel);
        }
        // POST: FlightTravelClasses/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditClass(FlightTravelClassModel flightTravelClass)
        {
            IEnumerable<TravelClass> travelClass = flightBL.GetTravelClass();
            ViewBag.ClassId = new SelectList(travelClass, "ClassId", "ClassName");
            if (ModelState.IsValid)     //condition pass when all the model state validation is true
            {
                FlightTravelClass edit = AutoMapper.Mapper.Map<FlightTravelClassModel, FlightTravelClass>(flightTravelClass);     //Auto Mapper model to entity
                flightBL.EditClass(edit);
                return RedirectToAction("DisplayFlight","Flight");
            }
            ViewBag.Flight_Id = new SelectList(flightBL.DisplayFlight(), "FlightId", "FlightName", flightTravelClass.FlightId);
            ViewBag.Class_Id = new SelectList(flightBL.GetTravelClass(), "ClassId", "ClassName", flightTravelClass.ClassId);
            return View(flightTravelClass);     //Calling View for the Edit Class(when the ModelState is in valid)
        }

        [HttpGet]
        // GET: FlightTravelClasses/Delete/5
        public ActionResult DeleteClass(int id)
        {
            FlightTravelClass flightTravelClass = flightBL.GetDetailsClass(id);
            ViewBag.ClassId = new SelectList(flightBL.GetTravelClass(), "ClassId", "ClassName");
            FlightTravelClassModel delete = AutoMapper.Mapper.Map<FlightTravelClass,FlightTravelClassModel>(flightTravelClass);     //Auto Mapper entity to model
            return View(delete);
        }

        // POST: FlightTravelClasses/Delete/5
        [HttpPost]
        public ActionResult DeleteClass(FlightTravelClassModel delete)
        {
            FlightTravelClass flightTravelClass = AutoMapper.Mapper.Map<FlightTravelClassModel, FlightTravelClass>(delete);     //Auto Mapper model to entity
            flightBL.DeleteFlightTravelClass(flightTravelClass);
            return RedirectToAction("DisplayFlight","Flight");
        }
    }
}

FlightMVC/Views/FlightTravelClasses/CreateClass.cshtml
@model OnlineFlightBooking.Models.FlightTravelClassModel

@{
    ViewBag.Title = "GetClass";
}

<h2>FlightTravelClass</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <table id="normal">
        @Html.HiddenFor(model => model.FlightId)
        <tr>
            <td> @Html.LabelFor(model => model.ClassId)</td>
            <td>
                @Html.DropDownList("ClassId", (IEnumerable<SelectListItem>)ViewBag.ClassId)
                @Html.ValidationMessageFor(model => model.ClassId)
            </td>
        </tr>
        <tr>
            <td>@Html.LabelFor(model => model.SeatCount)</td>
            <td>
                @Html.EditorFor(model => model.SeatCount)
                @Html.ValidationMessageFor(model => model.SeatCount, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.SeatCost)
            </td>
            <td>
                @Html.EditorFor(model => model.SeatCost)
                @Html.ValidationMessageFor(model => model.SeatCost, "", new { @class = "text-danger" })
            </td>
        </tr>
        <tr>
            <td>
                <input type="submit" value="Create" class="buttonstyle" />
            </td>
            <td>
                @Html.ActionLink("Back to List", "DisplayClass")
            </td>
        </tr>
    </table>
}

FlightMVC/Views/FlightTravelClasses/DeleteClass.cshtml
@model OnlineFlightBooking.Models.FlightTravelClassModel

@{
    ViewBag.Title = "Delete";
}

<h2>Flight Delete Conformation!!</h2>

<h3>Are you sure you want to delete this?</h3>
<link rel="stylesheet" href="~/Content/OnlineFlightBookingStyle.css" />
@using (Html.BeginForm("DeleteClass", "FlightTravelClasses"))
{
    @Html.HiddenFor(Model => Model.FlightTravelClassId)
    <div>
        <h4>FlightTravelClass</h4>
        <table id="normal">
            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.FlightId)
                </td>
                <td>
                    @Html.DisplayFor(model => model.FlightId)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.ClassId)
                </td>
                <td>
                    @Html.DisplayFor(model => model.ClassId)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.SeatCount)
                </td>
                <td>
                    @Html.DisplayFor(model => model.SeatCount)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.SeatCost)
                </td>

                <td>
                    @Html.DisplayFor(model => model.SeatCost)
                </td>
            </tr>
            <tr>
                <td>
                    <input type="submit" value="Delete" class="buttonstyle"/> 
                </td>
                <td>
                    @Html.ActionLink("Back to DisplayFlight", "DisplayFlight", "Flight")
                </td>
            </tr>
        </table>
    </div>
}

FlightMVC/Views/FlightTravelClasses/Details.cshtml
@model OnilneFlightBooking.Entity.FlightTravelClass

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>FlightTravelClass</h4>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Flight.FlightName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Flight.FlightName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TravelClass.ClassName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TravelClass.ClassName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SeatCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SeatCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SeatCost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SeatCost)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.FlightTravelClassId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FlightMVC/Views/FlightTravelClasses/DisplayClass.cshtml
@model IEnumerable<OnilneFlightBooking.Entity.FlightTravelClass>

@{
    ViewBag.Title = "DisplayClass";
}

@if(TempData["FlightId"]!=null)
{
    TempData.Keep("FlightId");
}
<h2>Display</h2>
<p>
    @Html.ActionLink("Create New", "CreateClass")
</p>
<table id="TableStyle">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Flight.FlightName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TravelClass.ClassName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SeatCount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SeatCost)
        </th>
        <th>
            Modify
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Flight.FlightName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TravelClass.ClassName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SeatCount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SeatCost)
            </td>
            <td>
                @Html.ActionLink("Edit", "EditClass", new { id = item.FlightTravelClassId }) |
                @Html.ActionLink("Delete", "DeleteClass", new { id = item.FlightTravelClassId })
            </td>
        </tr>
    }

</table>
@Html.ActionLink("Back to flight display", "DisplayFlight", "Flight")

FlightMVC/Views/FlightTravelClasses/EditClass.cshtml
@model OnlineFlightBooking.Models.FlightTravelClassModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>
<link rel="stylesheet" href="~/Content/OnlineFlightBookingStyle.css" />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <h4>FlightTravelClass</h4>
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.FlightTravelClassId)
    @Html.HiddenFor(model => model.FlightId)
    @Html.HiddenFor(model => model.ClassId)
    <table id="normal">
        <tr>
            <td>
                @Html.LabelFor(model => model.FlightId, "Flight_Id")
            </td>
            <td>
                @Html.DisplayFor(model => model.FlightId, "Flight_Id")
                @Html.ValidationMessageFor(model => model.FlightId, "", new { @class = "required" })
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.ClassId)
            </td>
            <td>
                @Html.DropDownListFor(model => model.ClassId,ViewBag.ClassId as SelectList)
                @Html.ValidationMessageFor(model => model.ClassId, "", new { @class = "required" })
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.SeatCount)
            </td>
            <td>
                @Html.EditorFor(model => model.SeatCount)
                @Html.ValidationMessageFor(model => model.SeatCount, "", new { @class = "required" })
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.SeatCost)
            </td>
            <td>
                @Html.EditorFor(model => model.SeatCost)
                @Html.ValidationMessageFor(model => model.SeatCost, "", new { @class = "required" })
            </td>
        </tr>
        <tr>
            <td>
                <input type="submit" value="Update" class="buttonstyle" />
            </td>
        </tr>
    </table>
}
<div>
    @Html.ActionLink("Back to List", "DisplayClass")
</div>