FlightMVC/Controllers/FlightController.cs
using OnlineFlightBooking.Models;
using OnilneFlightBooking.Entity;
using System.Collections.Generic;
using System.Web.Mvc;
using OnlineFlightBooking.BL;

namespace OnlineFlightBooking.Controllers
{
    [Authorize(Roles="admin")]
    public class FlightController : Controller
    {

        // GET: Fli
        IFlightBL flightBL;
        public FlightController()
        {
            flightBL = new FlightBL();
        }
        public ActionResult DisplayFlight()
        {
            IEnumerable<Flight> flights = flightBL.DisplayFlight();
            IEnumerable<FlightTravelClass> flightTravelClasses = flightBL.GetFlightTravelClass();
            IEnumerable<TravelClass> travelClasses = flightBL.GetTravelClass();
            TempData["FlightTravelClass"] = flightTravelClasses;
            TempData["TravelClass"] = travelClasses;
            List<FlightModel> flightModels = new List<FlightModel>();
            foreach(var flight in flights)
            {
                FlightModel flightModel = AutoMapper.Mapper.Map<Flight, FlightModel>(flight);       //Auto Mapper entity to model 
                flightModels.Add(flightModel);
            }
            return View(flightModels);      //Calling View for the Display Flight
        }
        // GET: AddFlight
        [HttpGet]
        public ActionResult AddFlight()
        {
            return View();      //Calling View for the Add Flight
        }
        // POST: AddFlight
        [HttpPost]
        public ActionResult AddFlight(FlightModel add)
        {
            if (ModelState.IsValid)     //condition pass when all the model state validation is true
            {
                add.TotalSeat = 0;
                Flight flight = AutoMapper.Mapper.Map<FlightModel, Flight>(add);   //Auto Mapper model to entity
                flightBL.AddFlight(flight);
                TempData["message"] = "Flight added successfully";
                TempData["FlightId"] = flight.FlightId;
                return RedirectToAction("CreateClass", "FlightTravelClasses");
            }
            return View();      //Calling View for the AddFlight (when the ModelState is in valid)
        }
        // GET: EditFlight
        [HttpGet]
        public ActionResult EditFlight(int Id)
        {
            Flight flight = flightBL.GetFlightDetails(Id); 
            FlightModel flightModel = AutoMapper.Mapper.Map<Flight,FlightModel>(flight);   //Auto Mapper entity to model 
            return View(flightModel);       //Calling View for the Edit Flight
        }
        // POST: EditFlight
        [HttpPost]
        public ActionResult EditFlight(FlightModel edit)
        {
            if (ModelState.IsValid)     //condition pass when all the model state validation is true
            {
                Flight flight=AutoMapper.Mapper.Map<FlightModel, Flight>(edit);     //Auto Mapper model to entity
                flightBL.UpdateFlight(flight);
                TempData["message"] = "Flight Updated successfully";
                TempData["FlightId"] = flight.FlightId;
                return RedirectToAction("DisplayClass", "FlightTravelClasses");
            }
            return View();      //Calling View for the EditFlight(when the ModelState is in valid)
        }
        // GET: DeleteFlight
        [HttpGet]
        public ActionResult DeleteFlight(int Id)
        {
            Flight flight = flightBL.GetFlightDetails(Id);
            FlightModel flightModel = AutoMapper.Mapper.Map<Flight, FlightModel>(flight);   //Auto Mapper entity to model 
            return View(flightModel);           //Calling View for the Delste Flight
        }
        // POST: DeleteFlight
        [HttpPost]
        public ActionResult DeleteFlight(FlightModel delete)
        {
            Flight flight = AutoMapper.Mapper.Map<FlightModel, Flight>(delete);     //Auto Mapper model to entity
            flightBL.DeleteFlight(flight);
            TempData["message"] = "Flight deleted successfully";
            return RedirectToAction("DisplayFlight");
        }
    }
}

FlightMVC/Views/Flight/AddFlight.cshtml
@model OnlineFlightBooking.Models.FlightModel

@{
    ViewBag.Title = "AddFlight";
}

<h2>AddFlight</h2>

@using (Html.BeginForm("AddFlight", "Flight", FormMethod.Post))
{
    <table id="normal">
        <tr style="border-spacing:10px">
            <td>@Html.Label("FlightName")</td>
            <td>
                @Html.TextBoxFor(model => model.FlightName, new {placeholder="Enter Flight Name", @MaxLength = 25 })
                @Html.ValidationMessageFor(Model => Model.FlightName, "", new { @class = "required" })
            </td>
        </tr>
        <tr>
            <td>@Html.Label("From Location")</td>
            <td>
                @Html.TextBoxFor(model => model.FromLocation, new {placeholder="Enter From Location", @MaxLength = 10 })
                @Html.ValidationMessageFor(Model => Model.FromLocation, "", new { @class = "required" })
            </td>
        </tr>
        <tr>
            <td>@Html.Label("ToLocation")</td>
            <td>
                @Html.TextBoxFor(model => model.ToLocation,new {placeholder="Enter To Location" })
                @Html.ValidationMessageFor(Model => Model.ToLocation, "", new { @class = "required" })
            </td>
        </tr>
        <tr>
            <td>@Html.Label("ArrivalTime")</td>
            <td>
                @Html.TextBoxFor(model => model.Date,new {placeholder="Enter ArrivalTime",@type="date"})
                @Html.ValidationMessageFor(Model => Model.Date, "", new { @class = "required" })
            </td>
        </tr>
        <tr>
            <td>@Html.Label("Duration")</td>
            <td>
                @Html.EditorFor(model => model.ArrivalTime,new {placeholder="Enter Duration", @type="time"})
                @Html.ValidationMessageFor(Model => Model.ArrivalTime, "", new { @class = "required" })
            </td>
        </tr>
        <tr>
            <td>
                <input type="submit" value="Register" class="buttonstyle"/>
            </td>
        </tr>
    </table>
    @Html.ActionLink("Go back to DisplayFlight", "DisplayFlight", "Flight")
}

FlightMVC/Views/Flight/DeleteFlight.cshtml
@model OnlineFlightBooking.Models.FlightModel

@{
    ViewBag.Title = "DeleteFlight";
}

<h2>DeleteFlight</h2>
<h3>Are you sure want to delete this?</h3>
<link rel="stylesheet" href="~/Content/OnlineFlightBookingStyle.css" />
@using (Html.BeginForm("DeleteFlight", "Flight"))
{
    @Html.HiddenFor(model => model.FlightId)
    <table id="normal">
        <tr style="border-spacing:10px">
            <td>@Html.LabelFor(model => model.FlightId)</td>
            <td>@Html.ValueFor(model => model.FlightId)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(model => model.FlightName)</td>
            <td>@Html.ValueFor(model => model.FlightName)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(model => model.FromLocation)</td>
            <td>@Html.ValueFor(model => model.FromLocation)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(model => model.ToLocation)</td>
            <td>@Html.ValueFor(model => model.ToLocation)</td>
        </tr>
        <tr> 
            <td>@Html.LabelFor(model => model.Date)</td>
            <td>@Html.ValueFor(model => model.Date)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(model => model.ArrivalTime)</td>
            <td>@Html.ValueFor(model => model.ArrivalTime)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(model => model.TotalSeat)</td>
            <td>@Html.ValueFor(model => model.TotalSeat)</td>
        </tr>
        <tr>
            <td colspan="2">
                <input type="submit" value="Delete" class="buttonstyle"/>
            </td>
        </tr>
        <tr>
            @Html.ActionLink("Go back to DisplayFlight", "DisplayFlight", "Flight")
        </tr>
    </table>
}

FlightMVC/Views/Flight/DisplayFlight.cshtml
@model IEnumerable<OnlineFlightBooking.Models.FlightModel>
@{
    ViewBag.Title = "Displayflight";
}
<link rel="stylesheet" href="~/Content/OnlineFlightBookingStyle.css" />
<h2>AdminPage</h2>
@*<h3>@TempData["message"]</h3>*@
<a>
    @Html.ActionLink("AddFlight", "AddFlight", "Flight")
</a>

<table id="TableStyle">
    <tr>
        <th>Flight Id</th>
        <th>Flight Name</th>
        <th>FromLocation</th>
        <th>ToLocation</th>
        <th>Date</th>
        <th>ArrivalTime</th>
        <th>TotalSeat</th>
        <th>Class</th>
        <th>Modification</th>
    </tr>
    @foreach (OnlineFlightBooking.Models.FlightModel flight in Model)
    {
        <tr style="text-align:center">
            <td>@flight.FlightId</td>
            <td>@flight.FlightName</td>
            <td>@flight.FromLocation</td>
            <td>@flight.ToLocation</td>
            <td>@flight.Date.ToLongDateString()</td>
            <td>@flight.ArrivalTime.ToLongTimeString()</td>
            <td>@flight.TotalSeat</td>
            <td>
                <table>
                    <tr>
                        <th>class</th>
                        <th>Available Seats</th>
                        <th>Booked Seats</th>
                    </tr>
                    @foreach (OnilneFlightBooking.Entity.FlightTravelClass flightTravelClass in (List<OnilneFlightBooking.Entity.FlightTravelClass>)TempData["FlightTravelClass"])
                    {
                        foreach (OnilneFlightBooking.Entity.TravelClass travelClass in (List<OnilneFlightBooking.Entity.TravelClass>)TempData["TravelClass"])
                        {
                            <tr>
                                @if(flightTravelClass.ClassId==travelClass.ClassId && flight.FlightId==flightTravelClass.FlightId)
                                {
                                    <td>
                                        @travelClass.ClassName
                                    </td>
                                    <td>
                                        @flightTravelClass.SeatCount
                                    </td>
                                    <td>
                                        @flightTravelClass.SeatBooked
                                    </td>
                                }
                            </tr>
                        }
                    }
                </table>
                </td>
                <td>@Html.ActionLink("Edit", "EditFlight", new { id = flight.FlightId }) | @Html.ActionLink("Delete", "DeleteFlight", new { id = flight.FlightId })</td>
            </tr>
        }
</table>

FlightMVC/Views/Flight/EditFlight.cshtml
@model OnlineFlightBooking.Models.FlightModel

@{
    ViewBag.Title = "EditFlight";
}

<h2>EditFlight</h2>
<link rel="stylesheet" href="~/Content/OnlineFlightBookingStyle.css" />
@using (Html.BeginForm("EditFlight", "Flight"))
{
    @Html.HiddenFor(model => model.FlightId)
<table id="normal">
    <tr style="border-spacing:10px">
        <td>@Html.Label("Flight Id")</td>
        <td>
            @Html.ValueFor(model => model.FlightId)
        </td>
    </tr>
    <tr>
        <td>@Html.Label("FlightName")</td>
        <td>
            @Html.EditorFor(model => model.FlightName, new { @MaxLength = 25 })
            @Html.ValidationMessageFor(Model => Model.FlightName, "", new { @class = "required" })
        </td>
    </tr>
    <tr>
        <td>@Html.Label("From Location")</td>
        <td>
            @Html.EditorFor(model => model.FromLocation, new { @MaxLength = 10 })
            @Html.ValidationMessageFor(Model => Model.FromLocation, "", new { @class = "required" })
        </td>
    </tr>
    <tr>
        <td>@Html.Label("ToLocation")</td>
        <td>
            @Html.EditorFor(model => model.ToLocation)
            @Html.ValidationMessageFor(Model => Model.ToLocation, "", new { @class = "required" })
        </td>
    </tr>
    <tr>
        <td>@Html.Label("Date")</td>
        <td>
            @Html.EditorFor(model => model.Date)
            @Html.ValidationMessageFor(Model => Model.Date, "", new { @class = "required" })
        </td>
    </tr>
    <tr>
        <td>@Html.Label("ArrivalTime")</td>
        <td>
            @Html.EditorFor(model => model.ArrivalTime)
            @Html.ValidationMessageFor(Model => Model.ArrivalTime, "", new { @class = "required" })
        </td>
    </tr>
    <tr>
        <td>@Html.Label("TotalSeat")</td>
        <td>
            @Html.ValueFor(model => model.TotalSeat)
        </td>
    </tr>
    <tr>
        <td>
            <input type="submit" value="Update" class="buttonstyle"/>
        </td>
    </tr>
</table>
    @Html.ActionLink("Go back to DisplayFlight", "DisplayFlight", "Flight")
}